# Generated by Django 3.1.3 on 2020-11-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20201123_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='subject',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college_name', 'branch', 'subject', 'session')},
        ),
    ]
