# Generated by Django 3.1.3 on 2020-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20201123_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
