# Generated by Django 3.1.3 on 2020-11-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_colleges_valid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college_name',)},
        ),
    ]
