# Generated by Django 3.1.3 on 2020-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_auto_20201126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='exam',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], default='major', max_length=20),
        ),
        migrations.AddField(
            model_name='colleges',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college_name', 'branch', 'subject', 'year', 'exam')},
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='session',
        ),
    ]
