# Generated by Django 3.1.3 on 2020-11-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20201126_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together=set(),
        ),
    ]
