# Generated by Django 3.1.3 on 2020-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_auto_20201126_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='college_name',
            field=models.CharField(default='NIT Srinagar', max_length=50),
        ),
    ]
