# Generated by Django 3.1.3 on 2020-11-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_auto_20201126_2359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college_name', 'branch', 'subject', 'year', 'exam')},
        ),
    ]
