# Generated by Django 3.1.3 on 2020-11-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_auto_20201127_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together=set(),
        ),
    ]
