# Generated by Django 3.1.3 on 2020-12-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0015_auto_20201127_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
