# Generated by Django 3.1.3 on 2020-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0016_auto_20201205_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
