# Generated by Django 3.1.3 on 2021-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0017_colleges_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='year',
            field=models.CharField(default='2017', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college_name', 'branch', 'subject', 'year')},
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='exam',
        ),
    ]
