# Generated by Django 3.1.3 on 2020-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='boards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='views',
            name='colleges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='views',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='views',
            name='home',
            field=models.IntegerField(default=0),
        ),
    ]
