# Generated by Django 3.1.3 on 2020-12-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201124_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='views',
        ),
    ]
