# Generated by Django 3.1.3 on 2020-11-16 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=50)),
                ('class_number', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sereis', models.CharField(max_length=10)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
