# Generated by Django 3.1.3 on 2020-11-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boards',
            unique_together={('board_name', 'class_number', 'year', 'sereis')},
        ),
    ]
