# Generated by Django 3.1.3 on 2020-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20201126_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
