# Generated by Django 3.1.3 on 2020-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20201127_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boards',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='boards',
            constraint=models.UniqueConstraint(fields=('board_name', 'class_number', 'subject', 'year', 'sereis'), name='unique board'),
        ),
    ]
