# Generated by Django 3.1.3 on 2020-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20201127_2235'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boards',
            constraint=models.UniqueConstraint(fields=('board_name', 'class_number', 'subject', 'year', 'sereis'), name='unique board'),
        ),
    ]
