# Generated by Django 3.1.3 on 2020-12-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20201128_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='sereis',
            new_name='series',
        ),
    ]
