# Generated by Django 3.1.3 on 2020-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20201205_1311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boards',
            name='unique board',
        ),
        migrations.AddConstraint(
            model_name='boards',
            constraint=models.UniqueConstraint(fields=('board_name', 'class_number', 'subject', 'year', 'series'), name='unique board'),
        ),
    ]
