# Generated by Django 3.1.3 on 2020-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20201205_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
